project:
  type: website

website:
  title: "Eines de l'Institut Metròpoli"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - visualitzacio.qmd
      - analisis.qmd
      - tractament.qmd
      - organitzacio.qmd

format:
  html:
    theme: 
      light: pulse
      dark: solar
    css: styles.css
    toc: true

editor: visual

